server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: HelloOne
          uri: lb://first-service
          predicates:
            - Path=/HelloOne/**
        - id: HelloTwo
          uri: lb://second-service
          predicates:
            - Path=/HelloTwo/**
        - id: Factory
          uri: lb://factory-service
          predicates:
            - Path=/Factory/**